# Generated by Django 3.2.4 on 2021-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('cep', models.IntegerField()),
                ('endereco', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('email', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
