# Generated by Django 3.2.4 on 2021-06-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_motocicletas_vendas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='data_venda',
            new_name='dataVenda',
        ),
    ]
