# Generated by Django 3.2.4 on 2021-06-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_data_venda_vendas_datavenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='dataVenda',
        ),
    ]
