# Generated by Django 3.2.4 on 2021-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vendas_datavenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='dataVenda',
            field=models.CharField(default=12042021, max_length=200),
            preserve_default=False,
        ),
    ]
